### ISSUE TITLE
Error when I install using command : python3 setup.py install

### ISSUE THREAD

**Issue by necklinux** [rdhyee/py-applescript#12]
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    'Programming Language :: Python :: 3'
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/dist.py", line 426, in __init__
    k: v for k, v in attrs.items()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 267, in __init__
    getattr(self.metadata, "set_" + key)(val)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 1227, in set_requires
    distutils.versionpredicate.VersionPredicate(v)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/versionpredicate.py", line 114, in __init__
    raise ValueError("expected parenthesized list: %r" % paren)
ValueError: expected parenthesized list: '-core'

According to https://stackoverflow.com/questions/16127080/setup-py-expected-parenthesized-list-when-required-package-name-contains-a-dash

In file setup.py , change "requires" to "install_requires" and then  everything is good.

**Comment by rdhyee** [comment]
Thank you @necklinux for reporting this issue and specifying the fix!  I've updated the master branch and am now working on updating PyPI -- I just need to remind myself how to do so.
